data:
  processed_data_path: "data/processed/feature_engineered_data.csv"
  inference_data_path: "data/processed/new_week_data.csv"
  train_data_path: "data/processed/train_data.csv"

aws:
  s3_bucket: "avinda-shamal-retail-demand-forecasting"

mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "RetailForecastingModel"

model:
  target: "Weekly_Sales"
  date_column: "Date"
  split_date: "2012-01-01"
  feature_exclude: ["Date", "Weekly_Sales"]
  param_grid:
    n_estimators: [300, 500, 700]
    learning_rate: [0.01]
    max_depth: [4, 6, 8]
  model_base_params:
    objective: "reg:squarederror"
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
    eval_metric: "rmse"
    verbosity: 0
  early_stopping_rounds: 10
  n_cv_splits: 5
  grid_search_settings:
    scoring: "neg_root_mean_squared_error"
    n_jobs: -1
  registry_name: "RetailForecastingModel"
  output_path: "models/xgb_model.pkl"
  params_output_path: "models/best_params.json"

output:
  predictions_output_path: "outputs/batch_predictions.csv"